development:
  adapter: postgresql
  database: iwilltravel_development
  pool: 5
  timeout: 5000
  username: cs

test:
  adapter: postgresql
  database: iwilltravel_test
  pool: 5
  timeout: 5000
  username: cs

production:
  adapter: postgresql
  database: iwilltravel_production
  pool: 5
  timeout: 5000
  username: cs
